### ISSUE TITLE
Seconds

### ISSUE THREAD

**Issue by finnie2006** [ElToberino/Tobers_Multidisplay#6]
The project is super cool, only thing that i am missing are second for the clock, that would be nice
Edit: another suggestion is to set a interval to scroll the data, and by default show the clock

**Comment by finnie2006** [comment]
Also after i set the wifi, the matrix says getting data and then it gets black

**Comment by finnie2006** [comment]
![image](https://user-images.githubusercontent.com/57916807/202550248-cfe4b0a8-8913-48e2-ab85-2795fe864159.png)

**Comment by ElToberino** [comment]
Thanks for your kind words.
The display is showing seconds in time-only mode with all other messages deactivated. You can try it.

Exploring my code you will see that I've added a lot of comments with hints and links. So you should be able to change the code according to your needs, implement new features etc.

I try to keep this project up to date and running with new and updated libraries and cores, but I don't think I'll add or change functions. If you want to do so, just fork my repo and give it a try.

Best regards!

**Comment by finnie2006** [comment]
Hm, i will give it a try

**Comment by finnie2006** [comment]
Having no luck yet
`````void displayTime() {                                                                // standard case: if messages other than time are activated
  static time_t lastsecond = 0;
  time_t now = time(&now);
  localtime_r(&now, &tm);
  if (tm.tm_sec != lastsecond) {
    lastsecond = tm.tm_sec;
    if (enableTime==1){
      strftime (timeshow, sizeof(timeshow), "%H:%M:%S", &tm);
     #ifdef DEBUG 
      Serial.print("current time: ");
      Serial.println(timeshow);
     #endif
    }
  }
    
  if (tm.tm_hour == 0 && tm.tm_min == 0 && tm.tm_sec == 0) makeDate();              // at 0:00 make new date
}
`````
I tried this by adding %S it kinda works, it does display the seconds, but it does not update the seconds like in the display only time, what line am i missing?

Also how can i make the specialcase==2 pause value configurable using the web interface

**Comment by ElToberino** [comment]
That is not as simple.
Before changing the program you should take a look at the [examples of Parola library](https://github.com/MajicDesigns/MD_Parola/blob/8bfa9067cd1a31d204c7ee48458ea89e50b11d8b/examples/Parola_Animation_2Speed/Parola_Animation_2Speed.ino) to figure out how displaying messages works. I know my program is very large - but that's why I added a lot of comments.
It's the same with changing web interface: this can't be done without knowing how webserver, json etc. work. There are a lot of good examples availabe in the web, please take a look at it. Just search for ESP8266 webserver.

This was also the way for me to write this program; before I didn't know very much about programming. As I said, the code is a little complex and so are potential changes. Please understand that I cannot change the program according to special demands - this is my hobby and I have other projects running. I always check the program when libraries or cores are updated to keep it up to date - this is laborious enough.

So I can really recommend to work it out for yourself and wish you good effort!
(I will close this because it's not an issue)

**Comment by finnie2006** [comment]
I guess i will just use clock only mode then

**Comment by finnie2006** [comment]
I tried for some more hours but i was not able to get it to work correctly
